### ISSUE TITLE
Cannot reedit file

### ISSUE THREAD

**Issue by dl2sba** [PredatH0r/ChanSort#10]
I exported the list from my SAMSUNG UE48JS909 to a USB stick.
Editing works fine in ChanSort.
I saved the list under a new name in ChanSort.
The import to the TV works fine.
When I try to reopen the edited file I get this error message "File not found inside .zip: chmgt_type0001/chmgt.db"

Any idea how this can be resolved?

**Comment by PredatH0r** [comment]
When using "Save As", please only modify the file name at the end and not at the beginning.
ChanSort has to look at the beginning of the file name to find out what sort of channel list it is.
.zip files can be either Samsung or Toshiba, and in this case it tried to use the Toshiba loader instead of the Samsung Loader.

**Comment by dl2sba** [comment]
Thanks for your reply.

I loaded the list from 
   Channel_list_T-HKPDEUC-1217.0.tv
and saved it as 
   Channel_list_T-HKPDEUC-1217.0.2015-10-25.tv

I retested it and now it works for other files - hm - maybe a glitch?!

I'll keep an eye on this.

//Dietmar
