### ISSUE TITLE
How to suppress the Microsoft visual C++ Redistributable Package (x64) download dialog?

### ISSUE THREAD

**Issue by Mugridge** [PredatH0r/ChanSort#101]
ChanSort works fine without this package is installed. How can I suppress this message?

**Comment by PredatH0r** [comment]
The package is needed for channel lists that use a SQLite database format, like Panasonic, Toshiba, Samsung .zip and Hisense. If you either edit such a list or use it as a reference list, the program will fail without it.
To reduce the flood of emails asking "why the program does not work" I am showing a message box, when the package is not installed. You can either download and install the package, or ignore the message box.
BTW, ChanSort needs the x86 version, not the x64 version. Many people get that wrong and send me emails asking for help. That's why there's a message box for the correct download link.

**Comment by Mugridge** [comment]
You are right, I got the message with the (x86) version, I copied the text from another comment. My channellist is a single .scm file and I can edit it without this package.
Okay, now I know that there is now way to disable this box and that i don't have to search for a switch to do this. Now problem and thank you for your quick response.
