### ISSUE TITLE
error when storing zip for Samsung TV

### ISSUE THREAD

**Issue by cbielow** [PredatH0r/ChanSort#123]
I have a 
[Channel_list_T-KTM2DEUC-1153.3.zip](https://github.com/PredatH0r/ChanSort/files/2719379/Channel_list_T-KTM2DEUC-1153.3.zip), obtained from a Samsung 4K TV.
While the file was transferred via an NTFS Stick, I|m reasonably sure the export it not broken because I can open the ZIP file just fine (with 7-zip) and the sqlite files are also browsable using a DBEditor.

The problem is when ChanSort (2017-11-30) is trying to store the edited list. I get this error:
"An unexpected error occured. ..ZipException: Cannot find entry to delete at ...".
![grafik](https://user-images.githubusercontent.com/6008722/50573656-95de9480-0dd8-11e9-9c57-04d5fd11fee1.png)

The new zip file is written nevertheless, and has the same size as the original one, but the TV does not accept it (wrong format...). I understand, that the read from NTFS might be problematic, but I guess the ChanSort error message should also not be there in the first place.

ZIP file is attached (see above).

**Comment by PredatH0r** [comment]
It looks like you extracted the original .zip and re-zipped it, but with a wrong directory structure.

All SQLite database files should be in the root folder of the .zip, but in your sample list they are in a 'Channel_list_T-KTM2DEUC-1153.3 subfolder, which typically happens when you right-click a folder in Windows Explorer and select "add to zip".

I'll update ChanSort so that it won't read such files anymore to avoid such pit-falls.
