### ISSUE TITLE
Chansort does not display all channels from TLL file

### ISSUE THREAD

**Issue by Tokolossi** [PredatH0r/ChanSort#150]
Dear team,

I've copied the channel list from my TV (LG 55C97LA) and imported it to Chansort (version 29.08.19) but can't find most of the HD channels. Chansort says it found 450 satellite channels while the TV states over 1300 in the Channel Manager.
I've disabled all filters and tried different versions of Chansort as well. If I open the TLL file I can find HD Channels in the XML content but they are not shown in the tool.
Do you have an idea whats wrong with it?

Best regards
Yves
[GlobalClone00001.zip](https://github.com/PredatH0r/ChanSort/files/3808399/GlobalClone00001.zip)

**Comment by PredatH0r** [comment]
When you set up your TV and started the initial channel search, did you select a predefined option like "Astra 19.2E"?

I can see information about "Das Erste HD" in the <SatelliteDB><stDBLCNContextInfo><astServiceInfo><ServCount617> XML data element, but ChanSort ignores the whole <SatelliteDB> block.

ChanSort edits the channel information in <CHANNEL><DTV><ITEM>, but there is no item for "Das Erste HD". That's why you can't see the channel in ChanSort.

Frankly, I have never seen the <ServCountX> data block before. This might be something LG added later on any might be only available when using a predefined list. Either way, I strongly discourage from editing any lists that are based on LCN (=logical channel number) / predefined numbers that are provided by TV firmware or cable/sat operators. 
Predefined lists always caused problems with LG TVs in the past, where that LCN information wasn't even exported and got out-of-sync when the file was edited.
I recommend to clear the channel data and run a full blind scan, selecting neutral options like "other", "none" or similar when the TV asks for a Sat or Cable provider.

**Comment by Tokolossi** [comment]
Hi PredatH0r,

great catch! Indeed I started the channel search with a predefined option but since the channels where found and in the XML file I did not consider it as faulty. It works now with a complete search and Chansort is displaying the missing channels. Thank you, really appreciated!

BR
Tokolossi
