### ISSUE TITLE
[Strong][SRT7006] Support for DBM file edit

### ISSUE THREAD

**Issue by Commifreak** [PredatH0r/ChanSort#157]
Hi,

I own a Strong Receiver which uses DBM format. Since ChanSort currently has no support for it, I want to ask, if you could add it. Unfortunately, I dont have any clue what format this is.
[HB_DATABASE_1_18.zip](https://github.com/PredatH0r/ChanSort/files/4081400/HB_DATABASE_1_18.zip)

THANKS in advance :)

**Comment by PredatH0r** [comment]
From a first look, Strong seems to use the same (or a similar) file format as Xoro.
Unfortunately I don't have enough information about either to add support for it in ChanSort.
The files use a binary format that does not provide any clue to me as to what the various data values in the file actually mean. The only thing I can see from looking at the file content are satellite and channel names.

Maybe, if you could provide a bit more information, I can find out a bit more.
Are you using a cable, antenna or satellite - and which ones?
Could you make a photo of the channel list on your TVs menu (so I can see what order/number the channels have)?
What features does the TV's channel list edit menu offer (hiding, deleting, skipping, parental-locking, number of favorite lists)? It would be helpful to have sample channels in the file that use the various features.

I can't make any promises here, since reverse-engineering of a binary file format is time consuming, error-prone and in many cases impossible.

**Comment by Commifreak** [comment]
Hi,

yes, it seems that Xoro uses the same format. I found a software that could edit the files: https://www.setedit.de/SetEdit.php?spr=1&Editor=121&device=Comag . If you close after 19 edits, you can use is forever.
