### ISSUE TITLE
Can't see any channels in the TLL file cloned from LG TV.

### ISSUE THREAD

**Issue by WesGorgy** [PredatH0r/ChanSort#176]
Hello there,

I tried copying channels from my LG TV to a USB, i got a globalclone.tll file but it doesn't show any channels in Chansort application. I even tried Cloning the TV channels to the USB by using the "Hotel Mode", yet no luck.
TV model: LG 49UN7340PVC

Thank You.

[GlobalClone.zip](https://github.com/PredatH0r/ChanSort/files/4626895/GlobalClone.zip)
[GlobalClone00003.zip](https://github.com/PredatH0r/ChanSort/files/4626898/GlobalClone00003.zip)

**Comment by PredatH0r** [comment]
Your file is in a new format that is also used by the new CX series ... I guess this comes with WebOS 5.
The currently publicly available version of ChanSort can't load that format.
There is a beta-version that can read it, but I received reports that the TV won't load the modified data. I haven't had time to investigate yet, but hopefully I find some later today/tomorrow.
Since I don't have an LG TV that produces such files it is a tedious trial and error process depending a lot on user feedback.

**Comment by WesGorgy** [comment]
Thank you so much for your comment.
That actually explains why it is not working .. Looking forward to the next updates ..

**Comment by PredatH0r** [comment]
Please see the thread here for any news on this subject: https://github.com/PredatH0r/ChanSort/issues/172
On the bottom is a link to the new beta version 2020-05-15 that might finally work
