### ISSUE TITLE
How to let ChanSort show channels/positions 4000 upwards?

### ISSUE THREAD

**Issue by clsven** [PredatH0r/ChanSort#187]
On my Samsung TV the channel range from 1 to 66. Then a gap and continuation from 4000 upwards (with gaps).

I exported the chanlist to usb flash drive and load it into ChanSort.
Unfortunately only channels until 1001 are shown.

How can I tell ChanSort to show ALL channels (=from 4000 too)?

Claudia

**Comment by PredatH0r** [comment]
I'd need to see the channel list file myself to make an assessment.
Normally ChanSort shows all channels that are not marked as deleted. Detection of that flag differes between file formats (and there are several different Samsung formats) and between channel source (analog cable, digital cable, digital antenna, digital satellite, ...)

**Comment by clsven** [comment]
Here it is:
https://www.sendspace.com/file/yfsovn

**Comment by PredatH0r** [comment]
Channels 1-1879 (TV) and 2000-2508 (Radio) can be found on the "astra_192e" tab.
Then there are 66 channels on the dvbt tab (using number 1-64)

The channels with numbers 4000 and higher are on the "ipsrv" tab. Those are internet streaming channels.
There are a lot of duplicate numbers in the list (because there are duplicates in the file). I do not recommend to edit those channels, displaying them is an experimental feature at the moment. I do not know which of the duplicates is the one that the TV actually uses. 

![grafik](https://user-images.githubusercontent.com/6238104/90531894-e30ea600-e176-11ea-9de7-0f2309a2467e.png)
