### ISSUE TITLE
Error no read/write TTL - LG

### ISSUE THREAD

**Issue by mianrelie** [PredatH0r/ChanSort#188]
Hi!

LG 43UJ630V-ZA 
Software version 05.80.65
webOS version 3.8.0-61315 (dreadlocks2-dunggir)

Import TTL file...and...
![imagen](https://user-images.githubusercontent.com/6920773/92493923-627f1a80-f1f5-11ea-8f9b-c5855e3d8068.png)

**Comment by PredatH0r** [comment]
Can you please attach your TLL file here?
This is crucial to find out why it could not be loaded.
Thanks!

**Comment by mianrelie** [comment]
[GlobalClone00001.zip](https://github.com/PredatH0r/ChanSort/files/5189281/GlobalClone00001.zip)

**Comment by PredatH0r** [comment]
The file contains some garbage bytes in the middle and is not valid XML data.
This happens when either there are bad memory cells on the USB stick or the TV fails to properly write onto a stick which is formatted with NTFS.
Please try again using a different USB stick, preferrably formatted with FAT32.

![grafik](https://user-images.githubusercontent.com/6238104/92514921-0a571100-f213-11ea-84da-b8f5db0b66bc.png)
