### ISSUE TITLE
Looking for a Converter 

### ISSUE THREAD

**Issue by Stetto** [PredatH0r/ChanSort#194]
Hi, i am searching for a channel list converter vom LG to Samsung. With ChanSort that seems not possible or did i not find this function? 

Looking forward to get some tipps :D

**Comment by PredatH0r** [comment]
Direct conversion is impossible due to firmware-specific data inside the the files, which is needed for proper TV operation.
With ChanSort you can do the following:
- run a full channel scan on the TV that you want to reorder
- export the list and open it in ChanSort
- select the option to apply the same order from a different list (=reference list)
- select your already sorted list from the other TV as the reference
- save the file and import it back in your TV
