### ISSUE TITLE
Sony KDL-55W808C "invalid checksum"

### ISSUE THREAD

**Issue by TTLucian** [PredatH0r/ChanSort#197]
Sony KDL-55W808C
Android 7
firmware v5.435
sdb.xml "<FormateVer>1.1.0</FormateVer>"
Error:
"No plugin found to read/writesdb.xml....."
"File load exception: Invalid checksum....."

**Comment by PredatH0r** [comment]
Can you send me your file so I can take a look?
At the end of the list is a checksum that ChanSort validates when reading the file. If the saved checksum does not match the value that ChanSort calculates, ChanSort will refuse to load the file because normally that would indicate that the file is damaged or ChanSort is unable to calculate the correct checksum that the TV requires for importing the file back.

If the file was edited with some other tool (i.e. Notepad), the checksum will not match the rest of the file content.
You can open the file with Notepad again, go all the way to the bottom and search for \<Checksum... \</Checksum>.
Replace the value there ("0x...") with the calculated value that ChanSort shows in the error message.
After that you should be able to open the file with ChanSort.

**Comment by PredatH0r** [comment]
Recent versions of ChanSort no longer reject to open a file with an invalid check sum, when the rest of the XML is valid.
There seems to be an issue with the firmware that it sometimes writes incorrrect or stale checksums.
