### ISSUE TITLE
LG 43UN71006LB (webOS 5.1.0) TV import failure

### ISSUE THREAD

**Issue by zeus-olymp** [PredatH0r/ChanSort#199]
Hi all,
a few days ago I bought a LG 43UN71006LB Smart TV with webOS 5.1.0-3203. And guess what: moving channels is a pain! :-(
Luckily I found this tool for sorting the channels, but unfortunately is has not worked out although is seemed working till the very end. This is my experiance:
1) Did a channel search on TV in "others" mode, like described in the Wiki.
2) Veryfied, that the channels can be moved in the channel manager on TV.
3) Exported the channel list to USB-Stick.
4) Opened the channel list in ChanSort (2020-11-16).
5) Modified the channel list and saved it back to USB-Stick.
6) Imported the channel list from USB-Stick to TV. Notification on TV says: Done, restarting TV.
Until this point it looked pretty good. But then ...
7) After restart of TV, the channel list looked like before. No modifications obvious.
I don't know, if this is normal after importing a channel list, but for the first 30-60 seconds, the channels have all the number 0. Then, the numbers came back.

Does anyone has an idea what I need to do that is works?
If you are interested in the TLL files, here they are:
[TLL-files.zip](https://github.com/PredatH0r/ChanSort/files/5585556/TLL-files.zip)
The ZIP contains the following:
GlobalClone00001_1-original.TLL  --  Original export from TV
GlobalClone00001_2-ChanSort-modified.TLL  --  Modified file from ChanSort
GlobalClone00001_3-TV-modified.TLL  --  new export after moving 2 channel with channel manager on TV

Kind regards,
Stefan

**Comment by PredatH0r** [comment]
This matches the experience that was reported with the first release of ChanSort that had experimental WebOS 5 support.
It turned out that the TV was unable to import any list at all, even when it was not modified with ChanSort.

The experiment was:
- scan channels ("others" mode)
- export the list
- swap 2 channels through the TV's menu
- load the list back from USB
and then the list in the TV was still the swapped one, not the saved one loaded from the stick.

The user who helped with the test later reported that the import worked only when he made a factory reset before the import. That cleared the TV's channel list so it won't get "confused".
But I am not sure if this is really the only way - and if it works reliably. I assume this also clears other data like the WLAN and netflix/amazon prime passwords.

I'll take a closer look at your files tomorrow. If you want to try the import-after-reset approach I'd be happy to hear feedback from you if that works.

Regards,
Horst

**Comment by PredatH0r** [comment]
Sorry for my late reply. I finally found some time to look at your files.
I wish I had a solution, but every time I look at an LG file I get more questions than answers.

If I understand you correctly, you made a full channel search, swapped 2 channels in the TV's menu (I assume it was 98 ZDFinfo HD and 99 KiKA HD) and then exported the list as the "original" file. I can see the "userEditChNumber" and "userSelCHNo" set to "true" for only these 2 channels, That part looks fine.

I'm a bit puzzled though why you list contains 1617 channels (1436 TV + 181 radio) with the majority marked deleted (860) and many others with blank name and service type 0 (neither TV nor radio nor data). I haven't seen anything like that before from a clean full channel search. Astra 19.2 doesn't even have that many channels, so I suspect the TV mixed some garbage into the list. 

The "tv-modified" list only contains 1591 channels. Was there another scan inbetween and the list was only modified on the TV or was that the imported "chansort-modifed" further modified on the TV and then exported? 
It would be strange that the TV cuts channels off the list. Normally it just sets the "deleted=true" flag for the channels.

**Comment by PredatH0r** [comment]
It seems that webOS 5 issues are fixed by recent versions of LG firmware and ChanSort
