### ISSUE TITLE
Philips 50pus9005/12 Freesat EPG Slow

### ISSUE THREAD

**Issue by laythingy59** [PredatH0r/ChanSort#203]
Hi, firstly I'd just like to say this is a great tool. It's helped me fix one of several issues with the Philips TV guide.

I've been able to sort the channels so the freesat channels appear at the top.

The remaining issues I have are (and I think this is an issue with the TV itself)
1. I can't hide the scrambled channels - I've tried using chansort, but when I copy back to the TV they still appear at the end of the list.
2. I can't delete the scrambled channels - I've tried using chansort, but when I copy back to the TV, then entire ist gets reset to default (not in my sorted order)
3. I can't create favourites lists - The functionality doesn't seem to exsit on the TV, and I've tried to create a favourites list using chan sort, but when copying to the tv, nothing happens. 

The EPG loads extremely slowly and I think its becuase of the number of channels. Philips haven't replied to me about the epg yet.

Like I say, I think these are flaws with the TV, but I just wondered if anyone else had experienced these issues and whether there was anything you could do to help. 

Thanks
Adam

**Comment by Viburnum** [comment]
I experience the same problems on my 55pus7303

**Comment by PredatH0r** [comment]
Thanks for the feedback.
I don't have a Philips TV myself and used the Philips channel editor to make changes to the files and compare them before/after.
Since that editor has no function to hide/delete channels, I can't tell what changes would be needed in the file, and thus I can't implement that feature in ChanSort safely. I could remove a channel record, but I have no idea how that will affect the TV.

Some Philips TVs export a Favorites.xml file, others don't. I guess it is a feature only available to some models. I received a report that ChanSort has a bug and tries to save the Favorites.xml in the wrong directory. I'll be looking into that this weekend.

I can't really say anything about the EPG and slowdowns on the TV.
Some TVs load the EPG while they are in stand-by mode (and have to scan all channels for that), others only load the EPG data when you switch to a channel (and then loads EPG for all channels on the same frequency/transponder/MUX).

**Comment by Viburnum** [comment]
Thanks for the quick response. 
I took a look into the DVBS.xml file and it seems, that the tv resets/reorders the channels, that are not on the position according to the ChannelNumber. 
For instance I have "Sky Atlantic HD" on channel 16, but the entry appears in the xml file between channel 99 and 100. When I import the list on my tv and switch to channel 16, the channel is rearranged on channel 100. I rearranged the xml file manually, but this doesn't seems to help. So maybe that's more a symptom than the reason.

**Comment by PredatH0r** [comment]
Philips keeps checksums of all the files inside the chanLst.bin file.
So it most likely ignored your manually modified file when you tried to import it because the checksum doesn't match.
You can open and save your modified file with ChanSort, which will then write the correct checksum to chanList.bin.

**Comment by PredatH0r** [comment]
I made a modification a while back so that ChanSort reorders the XML "Channel" elements by their "ChannelNumber".
Since then I haven't received problem reports about Philips XML lists in a while, I assume this has fixed the problem.
