### ISSUE TITLE
Several problems exporting channellist onto TV.

### ISSUE THREAD

**Issue by CC-Army** [PredatH0r/ChanSort#205]
We have several problems exporting the edited tlls on LG GX and CX Series.
I know they aren´t supported yet but I hope the files can help analyzing the problem.

In some cases the edited list appears totally unaranged after exporting it on the TV.
Sometimes the edited list just appears for a second, to then disappearing on the TV.
Sometimes most of the edited list appears correctly with the exception of the 3rd channel, which is just skipped. So the list goes from 1, 2, 4, 5 and so on.

I hope the provided files help. I added the original files and the files that have been edited via Chansort.
[TLLs.zip](https://github.com/PredatH0r/ChanSort/files/5637163/TLLs.zip)

**Comment by PredatH0r** [comment]
Thanks for your files!
I compared original and edited with a the "KDiff3" tool that shows me the differences between the 2.
Chansort only changes the prNum, isInvisable (typo in the file format!), isSkipped, isUserSelCHNo fields, nothing else.

There is one last thing that I can think of now... in the original file the channel data records are also physically sorted... with prNum=1 beeing first, prNum=2 beeing second and so on. In the edited file I leave the physical order unchanged and only change the prNum value inside the data records. Maybe the firmware expects the channel records in the file to also be physically ordered.
I'll run a few more tests today, upload an experimental version that also reorders the records and put the link in here.
Hopefuly you or someone else can then provide me feedback if that works.

Cheers, Horst

**Comment by PredatH0r** [comment]
@CC-Army
I just realized that your files are using the webOS 3.5 format and not webOS 5 and on https://www.lg.com/uk/tvs/lg-OLED55C7V your TV is listed as "webOS 3.5: yes".
It's common that when a newer series comes out, older mid-/high-end models are relabeled and sold under the new series name as low-end models and run on the older technology / firmware.

So far I have not been aware of issues with webOS 3.5 lists (only webOS 5 lists).
Everything I wrote about the "CX" series so far was under the assumption that CX uses webOS 5, but that doesn't apply to your TV.

One thing you can try is reset your TV and import the list afterwards (without running a channel search).
Sometimes, especially after a firmware update, exporting/importing might not work properly anymore. 
I can only speculate that data stored in the TV, which was created by an older firmware, is not 100% compatible with newer firmware and only a reset (and eventually re-scan) gets the TV in a stable state.

**Comment by CC-Army** [comment]
The files include different cases. Some have been CX Models others GX Models. If you need some more specific information just tell me. I would be glad to help.

**Comment by PredatH0r** [comment]
Thanks for the clarifaction.
In the meantime I noticed it too that there were files from at least 3 different models:
- 13.10.20 from an OLED65C7BOZ with format version 1.100.000/400 (webOS 3.6.1-913, XML)
- 14.10.20 from an OLED55C7BOZ (same as above)
- 20.11.20 from an OLED65GX9LA with format 1.200.000/500 (webOS 5.1.1-3706, JSON)
- 27.11.20 from an OLED55C7BOZ (as in 14.10.20, but no "LG SmartTV\TN\INFO" file with firmware version)

Can you describe for each model separately (at least separate for the CX and GX models) what the issues are?
I need to keep these issues apart since the TV uses different firmware, different file formats and ChanSort uses different code for them. 

For webOS 3.x I'd expect the import to work correctly since your file (13.10) is from a full scan and not a predefined list.
If that file does not work properly, please let me know. I noticed there are changes to the "Hide" flag and to the "Skip"-Flag. I assume you started with an empty list, added the channels you want and let ChanSort add the remaining channels to the end as hidden+skip.
You could start with your Original file as a base line, select "Modify current list" and only make minor modification to it, like swap the first 2 channels and leave everything else as-is. If the TV accepts that list, move on with changes to more channel numbers. If that still works, try changing the "Skip" flag. Next attempt the "Hide" flag. That way we could narrow down what sort of change causes the trouble.

Your 14.10.20 file only contains changes to the "prNum" field. "isUserSelCHNo" is already set to 1 in the "Original" file, so I wonder if this is a file was exported from the TV after a modified list was imported before (e.g. the 13.10 file).

With 27.11.20 the Original file seems to be a clean full channel search again and the Edited list again with only a few visible channels and the rest skip+hidden, just like the scenario in 13.11.20.

The 20.11.20 is from the GX/webOS5 model. There is a folder "original tll" which contains a .bak file dated 6.10.2020 and a .tll file dated 20.11. with different file content. That .bak file seems to be the real original with a channel list from a full search, whereas the .tll file is already a modified with "Das Erste" moved to prNum 1. Or was this after a new channel search without a full scan (using a predefined list for Germany)? Predefined list's can't be editated - that's a know issue only the LG firmware developers can fix.
The "edited tll" folder contains the same .bak file and a newer modified .tll file. If that file is a modification of the already modified file from the "original tll" folder, the same restriction about presorted lists apply here.

Hopefully we can sort this out together, one model at a time :)

**Comment by PredatH0r** [comment]
Closing this issue because there haven't been any problem reports in a long time regarding webOS 5 files.
Looks like the combination of LG firrmware updates and ChanSort updates finally did the job.
