### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by daniel-scholten** [PredatH0r/ChanSort#213]
Has anyone of ever used this software? I checked eight tvs from the past decade which are all in the list of suported models. Not one had export/import functions. With LG, I wasn't even able to retrieve basic software information.

**Comment by PredatH0r** [comment]
https://www.chip.de/downloads/ChanSort-ChannelSort_60828875.html  - more than 780k downloads alone from chip.de
So yes, someone has used this software.
If you click on the Wiki link above you will find the information you seek, including instructions for LG.
And I suggest to read them carefully, because LG has made the import/export a mine field with barbed trip wires.
