### ISSUE TITLE
Template channel filters have no effect

### ISSUE THREAD

**Issue by Double-A-92** [PredatH0r/ChanSort#217]
When trying to use a template the checkboxes for "Eingang" and "Sendertyp" (and maybe "Signaltyp" too) don't actually filter anything.

I noticed this when trying to exclude radio channels, but they were included anyway.

![image](https://user-images.githubusercontent.com/2192982/103449178-df526a80-4ca4-11eb-9942-6ffb7e3fe1cb.png)

**Comment by PredatH0r** [comment]
In version 2021-01-24 I made some changes to how reference lists are applied.

Generally, when a channel does not have any information whether it is antenna/cable/satellite/ip, this filter is ignored.
Same is true for the other filters.
It depends on the type of channel list you initially loaded, if such information is available.
I haven't tested if the older versions were broken, but with this version I could successfully open a .scm list with Astra channels and then applied one of the Astra reference lists, selecting only Radio.
If you want a list without radio channels, make sure your current list on the left side is empty - or select the option to clear the list when you apply the reference list. Otherwise all the previous channels stay there are you will be only reordering the TV channels.

**Comment by Double-A-92** [comment]
> It depends on the type of channel list you initially loaded, if such information is available.

I also used an .scm and the "Service Typ" is available and correct. E.g. I see the "SD-TV", "HD-TV", "Radio",  "Data" and so on.

I attached my original file from the TV if you want to test with it: 
[channel_list_UE46F5000_1201.zip](https://github.com/PredatH0r/ChanSort/files/5862238/channel_list_UE46F5000_1201.zip)

**Comment by PredatH0r** [comment]
There have been a couple program updates regarding handling of reference lists.
I tried to apply the ch_astra192E reference list to your .scm file and this seems to work with the current program version.
