### ISSUE TITLE
Wrong service type is shown sd-tv insted hd-tv Phillips FW TPM 171. 

### ISSUE THREAD

**Issue by Janpopan** [PredatH0r/ChanSort#222]
DVB-C - Vodafone

Example 
Das Erste HD

is
sd-tv

should
hd-tv

`<Channel>
<Setup ChannelNumber="1" ChannelName="0x44 0x00 0x61 0x00 0x73 0x00 0x20 0x00 0x45 0x00 0x72 0x00 0x73 0x00 0x74 0x00 0x65 0x00 0x20 0x00 0x48 0x00 0x44 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00" ChannelLock="0" UserModifiedName="0" LogoID="1290" UserModifiedLogo="0" LogoLock="0" UserHidden="0" FavoriteNumber="0" Scrambled="0"></Setup>
<Broadcast UniqueID="12" ChannelType="3" Onid="1" Tsid="1051" Sid="1" Frequency="330" Modulation="256" ServiceType="1" Bandwidth="8" SymbolRate="6902000" DecoderType="2" NetworkID="61444" StreamPriority="0" SystemHidden="0"></Broadcast>
</Channel>`

**Comment by Janpopan** [comment]
So there is no data in the XML about sd-tv or hd-tv. Your solution in ChanSort_2021-01-17 is good.

Should this info in some kind of documentation or wiki?

Or a bug report to Phillips? ;)

**Comment by Double-A-92** [comment]
Maybe there is information in **ChannelType="3"**. But currently only **ServiceType="1"**seems to be used, which maps to SD-TV.

**Comment by PredatH0r** [comment]
The **ServiceType** attribute only indicates 1=TV, 0=Radio and does not correspond to the DVB specification's "Service Type", which would give more detailed information.
I looked at the ChannelType and didn't see any values other than "3" in any DVB-T, DVB-C or DVB-S channel. I can only guess that it means "DVB". I don't have any files with analog channels or ATSC (US digital TV standad) to verify my assumtion.

Anyhow... ChanSort now displays "TV" in the "Service Type" column instead of "SD-TV".
