### ISSUE TITLE
After using Best Fit (all columns) program not responding, crashes

### ISSUE THREAD

**Issue by Oto868** [PredatH0r/ChanSort#232]
When I use function Best Fit (all columns) program crashes, see the printscreen below

![Snímka obrazovky 2021-04-13 104935](https://user-images.githubusercontent.com/66079081/114525182-2f4ab100-9c46-11eb-9b1a-07644936c15c.png)

**Comment by zoelechat** [comment]
Had same problem, looks it was due to some odd column width stored in config file (no idea how that occured).
Anyway, deleting that file for it to be recreated did the trick for me (C:\Users\username\AppData\Local\Chansort\config.xml)

I attach faulty config for potentially reproducing issue.
[config.zip](https://github.com/PredatH0r/ChanSort/files/6394380/config.zip)

**Comment by Oto868** [comment]
Big THX @zoelechat, issue solved 👍

**Comment by PredatH0r** [comment]
Version 2021-05-01 has a menu entry "Settings / Reset to defaults and restart" now which deletes the config file and restarts the program.
I have no idea why columns were super-sized or why "auto-size columns" (which is a function of the 3rd party DevExpress user interface library) failed. The new version also includes an updated version of the DevExpress library, so maybe that got fixed.

**Comment by zoelechat** [comment]
Possibly related to #237
