### ISSUE TITLE
Problem with Samsung lists and windows arm (Parallels virtual machine on apple m1)

### ISSUE THREAD

**Issue by ar1970** [PredatH0r/ChanSort#244]
I am not able to open a channel list from Samsung TV. The program interface stays empty after opening the samsung zip-file. Channel lists from LG TVs e.g. work fine. I use a virtual Windows 10 (arm) on an apple m1 with parallels 16.5. What are the differences between LG and Samsung channel lists?

**Comment by PredatH0r** [comment]
Can you send me your Samsung list please so I can take a look?
Do you get an error message when you try to open the Samsung list?

Samsung ".zip" files contain SQLite database files inside of it, which ChanSort reads through an external library that requires native code DLL specific for your machine architecture. ChanSort ships with DLLs for win-64, win-x86 and win-arm files (inside the "runtimes" subfolder of ChanSort). So on paper your arm-Architecture should be handled, but I have no installation to actually test this.

But maybe the "empty list" has nothing to do with that and is only caused by some specifics of your channel list file.

**Comment by ar1970** [comment]
Here is the Samsung zip-file. Btw, I can open it on another virtual machine (Windows7 with x86) architecture on another host hardware.

**Comment by ar1970** [comment]
I sent an email!

**Comment by PredatH0r** [comment]
Thanks for the quick response.
Unfortunately, when you replay to a github generated email, attachments get lost. So I did not receive the .zip.
Please attach it to the github thread on https://github.com/PredatH0r/ChanSort/issues/244
Thanks, Horst

**Comment by ar1970** [comment]
[Channel_list_T-MSMDEUC-1381.2.zip](https://github.com/PredatH0r/ChanSort/files/6800692/Channel_list_T-MSMDEUC-1381.2.zip)

**Comment by PredatH0r** [comment]
To be honest I have no idea how I could test ChanSort on an ARM architecture.
I just noticed that the "build target" of ChanSort was set to x86. I'm trying to create an "AnyCPU"-build and will upload it in a few minutes, hopefully that will work with ARM.

**Comment by ar1970** [comment]
Basically it works with arm (e.g. with LG lists) but not with samsung! I do not get any error messages! The program interface stays empty! There is nothing else.

**Comment by PredatH0r** [comment]
LG (and others) work because they do not use SQLite database files and therefore there is no dependency on native ARM code to load LG lists.
Samsung .zip lists however are SQLite databases and depend on native code in runtimes/win-arm/native/e_sqlite3.dll.
If that DLL supports the specific Apple M1 CPU, I don't know. And unfortunately I can't test that. I also tried to create a Virtual Machine on Azure, but there is no option to set up any ARM-CPU based VMs in Azure.

It's a long-shot, but maybe the new build (with updated SQLite library and compiled for AnyCPU) works now for you: https://chansort.com/ChanSort_2021-07-12.zip

**Comment by ar1970** [comment]
Wow. It seems to work! At least I can open the Samsung zip-file. I will do further tests and post another comment! Thank you very much.

**Comment by ar1970** [comment]
So, I didn't notice any restrictions. Many thanks!

**Comment by ar1970** [comment]
Issue can be closed!
