### ISSUE TITLE
Only some channels change it's order.

### ISSUE THREAD

**Issue by helios99** [PredatH0r/ChanSort#248]
Hello, i have sorted my channels and when i imported my list on TV only some channels are changed and some channels are not. I have a philips 50pus6203/12. I have uploaded my list from TV and ChanSort.
![20210721_183328](https://user-images.githubusercontent.com/53978625/126520074-3e40e738-9633-4b27-8cb5-d9f7e4bfd603.jpg)
![poza123](https://user-images.githubusercontent.com/53978625/126520216-5b607b09-960e-4363-b201-7636398acf15.PNG)

**Comment by PredatH0r** [comment]
I don't have any personal experience with Philips TVs and due to the large amount of different firmware versions with different channel list file formats and different behavior and features, it's difficult to provide any help.
Some users reported they had to power off the TV (unplug it) and then restart the TV before the list was fully applied.
Others needed to import the same list twice in a row.

Could you please make a .zip of your "ChannelMap" folder and its subfolders and upload it directly here on github (because e-mail attachments will get lost)?
The large .tar.gz file with channel icons is not needed.

Thanks,
Horst

**Comment by helios99** [comment]
Thank you for your answer. I will try to import the same list twice. I upload the "Channel List" folder here.

**Comment by PredatH0r** [comment]
Sorry for the late reply.
I spent quite some time today trying to figure out what is going on with your TV.

After I restored the backup files (.bak) and opened your original list, I saw that ChanSort shows a big WARNING message that the list has checksum errors:

![grafik](https://user-images.githubusercontent.com/6238104/127201742-7342c0bb-a0a3-4dfe-8070-3f9e006dc6bb.png)

I can rule out a bad USB stick, so there must be something wrong with the state of your TV and its internal channel list.
This can happen due to firmware updates or maybe even when the cable TV provider sends out new predefined channel numbers (LCNs).

The dialog also suggests to reset the TV and run a new channel scan. Then the TV should be in a clean state and be able to export/import a list correctly.

Another indicator that there's something off with your TV is the fact that in the modified channel list there are no favorites defined, but the photo of your TV still shows the old favorites. It must have somehow mixed old and new data.

If you decide to run a new channel search, please let me know if it worked.

**Comment by PredatH0r** [comment]
After some changes the ChannelMap\_100 format was confirmed to be working now.
(There are actually 2 different versions of this format that require different handling, hence the initial confusion)
