### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by Jurgis2002** [PredatH0r/ChanSort#250]
Hello,

**_Sorry, I do not know how to fix the topic title, which I have not fully completed._**

I installed version ChanSort_2021-05-01. This version worked just fine. I was able to edit my Sony TV channels, everything worked perfectly. But today I start application and message about new version appears. I downloaded new version and unpack ZIP in HDD. After restart app I have this error:

![Sony dll error (2021-07-27)](https://user-images.githubusercontent.com/88085448/127345414-ff8a6eea-6556-48b3-974c-f5cebbff51ce.png)

Then I tried to launch previous version and it becomes broken also! (When I try to open sdb.xml data file.)

![Sony dll error](https://user-images.githubusercontent.com/88085448/127343258-e8b3f60b-6c40-4240-b9a0-e5f1e22c9f20.png)

Unfortunately, I do not remember how I installed this application. A simple copying of files from the ZIP archive gave this result. So I want to ask how to properly reinstall this app. How do I fix this error I'm getting at all.

My system is the most standard: a personal computer with Intel i5, Windows 10, 16 GB of memory, integrated graphics. All the most common and standard.

Please help me! Thanks a lot!

Jurgis

**Comment by PredatH0r** [comment]
Both versions of ChanSort work fine, but your new channel list file is broken.
The Sony loader reports that the file has an invalid checksum. If you try to load that file even without modifications back into your TV, it will be rejected.
It could be either that there is a problem with the USB stick and the data got corrupted due to that, or it is also possible that the TV already has bad data in its memory and writes that onto the stick.

First, try using a different USB stick or reformat your stick. Ideally it should be <= 32GB and formatted with FAT32 (not NTFS or exFAT). Try exporting the list again and open it with ChanSort.

If you get the same message again, you might have to reset your TV to factory defaults and run a new channel search. Sometimes after firmware updates the internal data gets corrupted and piles up. A reset should fix that.

If you want you can send me your channel list and I can take a look if the file content itself is corrupted.

**Comment by Jurgis2002** [comment]
Thank you very much!

The problem really was precisely in the data file. I just misunderstood the program's error message. After I did everything as you described, the problem disappeared!

Thank you very, very much!!!

Jurgis

**Comment by PredatH0r** [comment]
Glad to hear that you could solve the problem.
May I ask, was it just a problem with the USB stick or did you have to reset your TV?

**Comment by Jurgis2002** [comment]
I'm not sure about the fault of the USB stick, although I took another stick.

I think another channel editor is to blame - SONY's own editor. I did an experiment. Opened the data file in the SONY editor, moved several channels and saved the file. After that, in the ChanSort editor, I got exactly this error that I wrote about. It turns out that SONY's own editor spoils its own data file! It is interesting :-)

And here's what's interesting: the data file of the SONY editor is read by the TV without problems. It looks like the SONY TV does not check the checksums of the data files at all! 

Thank you very much for your help!

Jurgis
