### ISSUE TITLE
Philips 58PUS8545, Changes to anything breaks the channels

### ISSUE THREAD

**Issue by pbellefleur** [PredatH0r/ChanSort#257]
I see from other comments here Philips models seem to be a bit of a pain, I'm trying to get mine to have a usable channel list and not getting far.

From what I've seen, renumbering a channel does change the channel number in the list, but the channel on the new number will not tune in, and you are left with a placeholder with no channel name in its old location. Hiding or deleting a channel results in the channel being stripped of its channel name, but it still shows in the list.
[ChannelMap_110.zip](https://github.com/PredatH0r/ChanSort/files/7061970/ChannelMap_110.zip)

I did do the power cycle thing several times and the write it a few times as I have seen in other posts, but no luck. Willing to provide any files you might need to sort this out.

**Comment by PredatH0r** [comment]
Sorry for my late reply. Today I spent some time with another type of Philips list and I got some insights that could also apply to your situation.

Can you tell me what kind of edits you made to your channel list?
Did you delete channels or did you only try to change their program numbers?

Your .zip file contains a DVBS.xml.bak (which should be a backup copy of the DVBS.xml before any modifications) and a DVBS.xml. However these 2 don't seem to belong to each other. Your DVBS.xml has more lines than the .bak file, so I can only guess that there was another channel search + export in between and that the .bak is a stale left-over backup from an older export. This leaves me in a place where I can't compare the files or analyze the problem.

What I have learned by examining the other Philips list is that they always seem to store the channel list redundant in 2 separate files. One file is always a .bin with an unknown compression, which prevents me from editing it. The other file depends on the version of the Philips model/firmware and is in your case a .xml file.
While reordering was possible with edits to the .xml file, deleting a channel does not work as expected and causes side-effects.
So I am curious if your changes also contained deletions.

**Comment by pbellefleur** [comment]
Hi, thanks for looking into this.

I've actually tried a few things. First attempt was to delete the
unwanted/scrambled channels, and that didn't work, the channels would still
show in the list, they would just have no channel name.

I then tried to "hide" the unwanted ones and had the same result.

I then tried to just reorder them, moving the unwanted ones to the end of
the list, and while it did edit the channel names when I scrolled through,
it didn't actually tune anything correctly. I'm not sure but what I think
happened was it just changed the name but not the PID. So what was
originally on channel 3 was still tuning on channel 3, just with a new name.

I thought the file I sent was a clean one after deleting the satellite and
re-scanning, but I'm not sure if that creates a bak or not

**Comment by PredatH0r** [comment]
ChanSort creates a .bak if there is none yet. 
The TV however doesn't care about .bak files at all and if you export the list again on the same stick, there will be an old .xml.bak file (which was the original list from the first export) and a new .xml file from the latest export. When you edit the new .xml ChanSort won't overwrite the old .bak and I have no base line to know what was the state before the edits and after the edits.

There is another editor for the Philips ChannelMap_110 file format, called "Onka Philips Channel Editor". I looked at its source code and tried to replicate it's behavior in ChanSort. Its author made the impression that Onka works, despite only editing the .xml file (and not even updating the checksums inside chanLst.bin). So I assumed ChanSort should work too with the same changes made to the .xml files. However I don't have a Philips TV to run tests myself and verify the result.

One thing the Onka author writes on his web site is that when scanning channels, you have to select the option "All Channel Unsorted". I guess you used that one since there is no real pre-order other than alphabetically.

**Comment by PredatH0r** [comment]
I compared the result of Onka with the result of ChanSort.
When both start with the same input, they produce similar output. Onka unintentionally removes some data that was added to format version 110 and didn't exist in version 100, because it only knows how to handle version 100.

I suggest to start with a clean list (fresh from a channel search or at least from a fresh export) and edit that list with ChanSort, only moving channels and not deleting any. In the next update I will disable deleting for all Philips lists (that is, when saving the unassigned channels will be appended at the end of the list).

**Comment by pbellefleur** [comment]
So I did delete and re-scan clean. Got a new channel list file, opened in chansort, and moved one channel...BBC HD to Channel 1.

Wrote it to the TV and it didn't change anything. The BBC I moved was still present on its original channel, just stripped of its name.

Its very touchy in Onka...It seems I can only use the move channel buttons, if I go down the list and type in a new channel number, it seems to break the whole thing again.

**Comment by PredatH0r** [comment]
Thanks for your help and time!
Can you send me your new channel list please (including the DVBS.xml and DVBS.xml.bak files)?
I can then compare them and also check the differences between ChanSort's and Onka's changes.
I'd upload a new ChanSort version then, if you are willing to try.

**Comment by PredatH0r** [comment]
In the .zip file you linked in your first post, there are several .txt files (chanLst.txt, LNBs.txt, logo.txt).
Did you create these files or is that something the TV exported?
chanLst.txt looks like a .txt reference list exported with ChanSort, LNBs.txt looks hand-made and logo.txt is probably from the TV, but I have never seen it before.

**Comment by pbellefleur** [comment]
Ill get you what I have tonight when I get off work.

anything in that Zip was exactly as the TV exported it. Doesn't surprise me it's a bit wonky. Anything in the software that isn't run by the Android OS on this TV is a bit.....off.

**Comment by PredatH0r** [comment]
https://chansort.com/ChanSort_2021-09-01.zip modifies the DVBS.xml file almost the same way as Onka (except for marginalities).
The included ChanSort.Loader.Philips.ini file has a couple settings in the \[Map110\] section that can control how the file is modified. 
The default values in this build will remove the \<SatelliteListcopy\> XML element from the head of the file.
It keeps UserReorderChannel="0" (the previous version set it to 1 if the channel was moved), but Onka completely removes this value. You can set "userReorderChannel=remove" in the .ini to mimic Onka's behavior with ChanSort.
I hope this build allows you to swap channels 1 and 2 without any .ini tinkering.

**Comment by Console** [comment]
Just thought I'd mention I've also got this issue with a 50PUS8546/12 TV. Changes definitely occurred to the list, but also the list was definitely messed up when imported to the TV. Going to follow the steps above but if you need another TV's channel export to compare (those logo.txt, etc are indeed what the TV exports) just let me know.

**Comment by PredatH0r** [comment]
@Console It would be really helpful to see your channel list too.
The latest development version of ChanSort can be found on https://chansort.com/ChanSort_2021-09-05.zip
What version of ChanSort did you use that caused the mess? Was it the currently official 2021-07-27 or the 2021-09-01 linked in this thread?
I'm still not sure why Onka worked for pbellefleur and ChanSort didn't. I haven't received any feedback about version 2021-09-01 yet, so maybe that one works. If not, there are a couple settings in the .ini that might help do the trick.
But it is important to import a clean list back in the TV after every failed attempt (e.g. a copy of the originally exported list).
If the TV is already in a bad state, it won't properly load a list that would otherwise work.
Any help is appreciated. I'd love to get this issue resolved asap.

**Comment by Console** [comment]
So I can confirm, the 2021-09-01 build without the suggested change to the .ini file you mention above, allowed me to reorder all my channels on my Phillips 50PUS8546/12 

Deleting did not work (in previous build ChanSort_2021-07-27) it resulted in the same issues as raised by @pbellefleur. I haven't tried it in 09-01 build yet.

Hiding Channels doesn't seem to do anything at all.

I used a saved reference list to do the bulk of the reordering and that worked great.

Only major difference is none of the channels are deleted, just any unsorted ones are sent to the end and are visible regardless of what "hide channel" is set to it seems.

TV was set to show "all satellite channels" - I haven't tried it filtering yet.

You realise, with the recent update to the Phillps TV's in the UK disabling favourite channel lists and editing of channel lists because of a dispute with freesat this app... is the **ONLY** way someone can reorder the channels in their TV to make them into a sensible list. Thank you so much for creating it.

Happy to test more builds over the next few days if you like.

I will attach a fresh copy of my channel list exported from the TV later today (it's 2:30am here) as i've just seen your new comment above :)

**Comment by PredatH0r** [comment]
In the 2021-09-05 build there is a setting at the very bottom in the \[Map110\] section: allowDelete=false
If your TV exports only .xml files in the channellib and s2channellib folders, it may work to set allowDelete=true.
I disabled it for now because many Philips lists also export .bin files next to the .xml and in this case they need to be kept in the exact same record order and same record count. It seems like the .xml is used for the Menu and the .bin for the tuner. Deleting from the .xml would then result in desynced menu / tuner with wrong names and numbers for the actual channels.

**Comment by pbellefleur** [comment]
Sorry it took a while, but yes, the latest version I was able to re-order the channels at least to make the listing usable now, thank you. 

I did some reading around and there seem to be issues with the channel listing and the TV's freeview play certification, so favorites don't work anymore. If you tell the TV it isn't in the UK, it lets you set favorites normally, but some of the UK apps stop working.

**Comment by PredatH0r** [comment]
Thanks for your time and feedback.
I also looked at the other "ChannelMap_110" lists I received from other users and none included a chanlist.txt file. Since the content had the exact same format of a ChanSort reference file, I can only assume that it was actually written by ChanSort, maybe due to a click of the "Save reference list" button, which looks similar to the regular "Save" button.
Anyhow... Thanks again!
