### ISSUE TITLE
LG 49UF695V no load file

### ISSUE THREAD

**Issue by pepeEL** [PredatH0r/ChanSort#27]
Hi
i Have a problem. I exported to file my list channel from TV by service menu, when i try open this file in chansort (file name:xxUF695V-ZA00001.TLL) i have an error:
"Loader
Configuration doesn't contain Analog and DVB-C/T data mapping for lenght 284"

I only can load GlobalClone00001.TLL and show my channel. But in manuals in web tell that i should load file and edit xxUF695V-ZA00001.TLL

Please help me...
this is my files:

**Comment by PredatH0r** [comment]
Delete the ZA0001.TLL file from the stick and edit the GlobalClone file. 
Your TV will read it when the other file isn’t present.

I'm no longer supporting any of the binary file formats from LG now that a more genaral GlobalClone format is available.

**Comment by pepeEL** [comment]
And when i edit this file GlobalClone and import in TV i dont destroy my TV ?

**Comment by PredatH0r** [comment]
I haven't seen any reports so far that because of a GlobalClone file a TV got bricked.
There are a few problem reports that the TV may rearrange the channel again after importing the list.
The file format is the same across many models, but only a few seem to be affected and that only under certain conditions unknown to me. My only explanation is that a bugged firmware is causing it.
In case your TV is affect, you can simple reset it to factory default and try loading a backup of your list or run a new channel search.

**Comment by pepeEL** [comment]
Ok i import in TV GlobalClone and works ok. Maybe add in changelog that this soft support LG series UF with GlobalClone file.

**Comment by pepeEL** [comment]
Today i have a problem becuase i try enable on TV INSTALLATION MENU (as yesterday) and menu not show. I dont know why :( ?
