### ISSUE TITLE
Error on servicelist.db  Hisense

### ISSUE THREAD

**Issue by Rixxardo** [PredatH0r/ChanSort#272]
![Errore](https://user-images.githubusercontent.com/93721770/140332793-6f28759e-e0ab-4d37-94ad-88a456c407f3.jpg)
I have a Hisense 65a7gq and i have save channel.
I recive error "This is a predefined list and cannot be edided"
How i can resolve ?
Thanks in advance

**Comment by PredatH0r** [comment]
When you set up your TV and start a channel search, you MUST NOT select any network operator or presorted satellite list.
There should be a neutral choice like "Other" or "None".
Only then you get a list that can be reordered.
You may want to keep your current file in a save place on your PC to use it as a reference list and bring your new list in the same order as a starting point from where you make further modifications.

**Comment by Rixxardo** [comment]
Thanks, i try

**Comment by ZoNi-011** [comment]
Doesn't help here, channels are still "cannot be edited" :(
Hisense 50A7100F

**Comment by makru83** [comment]
Same Problem here.
Actually I tried several different methods of searching channels, but the Channels are always presorted,
no matter what choice I made.

**Comment by PredatH0r** [comment]
It also depends on the signal source.

For DVB-C (cable) and maybe DVB-T too, the network providers can send "Logical Channel Numbers" (LCN) which are used to preorder the list. TVs then often have an option in the menu to "auto update channels", meaning that they always update the channel list to whatever they receive from DVB-T/C. With auto-update disabled, you should be able to reorder the list.

DVB-S (statellite) typically does not use LCN (at least not Astra 19.2), because there is no single logical order across Europe. Depending on the country, different pre-ordering is needed. That's where the TV's firmware jumps in and provided preordered lists for specific satellite/country combinations. Those can't be reordered.

Hard to tell what is really the cause without having seen your actual channel list file.

**Comment by makru83** [comment]
Ok, it was my fault. Mixed up the Strings LCN with LNB. So switching off LCN fixes the Problem
