### ISSUE TITLE
GlobalClone00001.tll is not a supported GlobalClone XML file

### ISSUE THREAD

**Issue by cvectra** [PredatH0r/ChanSort#284]
Hi,
doesn´t work anymore with a LG-UH8509 , SW: 05.60.15   (i don´t know where to find WebOS Version)

Opening GlobalClone00001.tll with ChanSort_2021-10-24 shows:

**Es konnte kein Modul zum Lesen/Schreiben von D:\GlobalClone00001.tll-Dateien gefunden werden.
LG: (*.tll, xx*.xml): "D:\GlobalClone00001.tll" is not a supported GlobalClone XML file**
[GlobalClone00001.zip](https://github.com/PredatH0r/ChanSort/files/7963520/GlobalClone00001.zip)

Any Idea?
Thanks!

kind regards
Martin

**Comment by PredatH0r** [comment]
That's because your file is damaged.
Please use a USB stick formatted with FAT32 (usually requires a stick <= 16GB).
The LG firmware often produces corrupted files when writing to NTFS formatted sticks.

Corruption starts here with unmatched XML open/close tags and garbage data following a bit later:

![image](https://user-images.githubusercontent.com/6238104/151660534-180be1d7-74f0-4b0c-975a-a88988ef31dc.png)

**Comment by cvectra** [comment]
That´s it  :-)

I used a 2 GB stick formatted with FAT32, but the files could not be opened.
Now I used another 2GB Stick formatted with FAT and the file could be opened at once!

Thank you so much, great work!

Kind regards
Martin
