### ISSUE TITLE
Newbie: Save Reference List

### ISSUE THREAD

**Issue by Si2Bim** [PredatH0r/ChanSort#30]
Could somebody pls. elaborate what this function is about?
Thanks in advance for the help :-)

**Comment by ThomasCr** [comment]
you dont point us a function?!

**Comment by PredatH0r** [comment]
The function to export a reference list is a relic from older version of ChanSort. The ref list is a .csv text file which contains channel names, number, skip/lock/hide and favorites.
It's no longer needed because ChanSort can now directly use any supported TV channel list file as input (instead of the .csv) to reorder the currently open file.

**Comment by Si2Bim** [comment]
Thanks for the feedback. The ChanSort is rather useful. 🤗
