### ISSUE TITLE
Not all channel names are displayed (TV LG24MT58VF-PZ)

### ISSUE THREAD

**Issue by NetLights** [PredatH0r/ChanSort#301]
Hi.

I have a problem with displaying channel names from the **LG24MT58VF-PZ** TV model. The screenshot shows that the names of some channels are not in the list:
![LG](https://user-images.githubusercontent.com/80199543/184129802-3f041b98-8d13-411d-9132-1767d393e16d.png)

I have a second Samsung TV and there is no such problem with its channel list:
![Samsung](https://user-images.githubusercontent.com/80199543/184129805-3633b71d-befc-46d4-9ed5-caad20b35238.png)

Is it possible to make the list from LG to be displayed in full? In the attachment below, I added a list of channels from both TVs.
**LG:** [GlobalClone00001.zip](https://github.com/PredatH0r/ChanSort/files/9308402/GlobalClone00001.zip)
**Samsung:** [Channel_list_T-KTSDEUC-1290.3.zip](https://github.com/PredatH0r/ChanSort/files/9308396/Channel_list_T-KTSDEUC-1290.3.zip)

**Comment by PredatH0r** [comment]
Hi.

 

Unfortunately, there is nothing I can do.

The LG file simply does not contain any names for some channels.

 

For example, here is the complete data for channel number 14 from the file.

As you can see, the vchName contains only a single space, nothing else.

lengthOfVchName contains the value 9, which is clearly inconsistent with the data in vchName.

 



 

I guess not even the LG firmware developers know what this TV is really doing. Every single LG TV generation has its own share of anomalies and they tend to add more than they fix with every generation.

Samsung on the other hand has a very stable format and have never encountered issues with it, aside from broken files due to bad USB sticks.

 

 

Best regards,

Horst Beham

 

Von: NetLights ***@***.***> 
Gesendet: Donnerstag, 11. August 2022 14:13
An: PredatH0r/ChanSort ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [PredatH0r/ChanSort] Not all channel names are displayed (TV LG24MT58VF-PZ) (Issue #301)

 

Hi.

I have a problem with displaying channel names from the LG24MT58VF-PZ TV model. The screenshot shows that the names of some channels are not in the list:
 <https://user-images.githubusercontent.com/80199543/184129802-3f041b98-8d13-411d-9132-1767d393e16d.png> 

I have a second Samsung TV and there is no such problem with its channel list:
 <https://user-images.githubusercontent.com/80199543/184129805-3633b71d-befc-46d4-9ed5-caad20b35238.png> 

Is it possible to make the list from LG to be displayed in full? In the attachment below, I added a list of channels from both TVs.
LG: GlobalClone00001.zip <https://github.com/PredatH0r/ChanSort/files/9308402/GlobalClone00001.zip> 
Samsung: Channel_list_T-KTSDEUC-1290.3.zip <https://github.com/PredatH0r/ChanSort/files/9308396/Channel_list_T-KTSDEUC-1290.3.zip>

**Comment by NetLights** [comment]
Thank you for your reply. Next time when buying a TV, I will think ten times before taking LG again :)
