### ISSUE TITLE
Exchange Senderlist between 2 Panasonic TVs

### ISSUE THREAD

**Issue by AlexMuc2** [PredatH0r/ChanSort#302]
Hi all,
first, both Liste form TVs (TX-40CSF637 and TX-32ESN608) are recognised an can be edited. Thats very nice.
But now, how to "copy" the List from the TX-40 to the other TV. Simply exporting the senderlist import it in the Second TV results in "no file found" or something.
Looks like, that the file contains "something" which prohibit the import. It would be real nice, to have a simple way to "clone" the main Senderlist and the favorite lists A-D from one TV to th next one. Ive tried it with saving "the Master" as Referencelist but it didn't work for me. Perhaps I did it wrong?

**Comment by PredatH0r** [comment]
There is no direct "clone" or "Save As" feature, but the same result can be achieved by running a full channel search for the 2nd TV, export the list, open it with ChanSort and select to copy the order of another list, selecting your 1st TV's list.
When opening a list in ChanSort you will be asked whether you want to copy the order (or start from scratch or edit as-is).

**Comment by AlexMuc2** [comment]
Hmm, I’ve tried that and got not the result I wanted… I will give it another try. Are the differences between the „versions“ for TVs of Panasonic / same manufacturer so big that a „save as“ are to much work?

**Comment by PredatH0r** [comment]
ChanSort supports about a hundred different file formats, not a single one of them is documented by the manufacturers and all contain massive amounts of data with unknown meaning, which can't be generate "out of the blue" using another list as the source. That data can even change on the same TV model between firmware versions, so that's a bottomless pit that I'm not going into.

That's why it is always required to run a full channel scan on a TV and use it's very own data file to make minor modifications for just the channel numbers.

**Comment by AlexMuc2** [comment]
Thanks a lot for this statement and I can understand that you don’t go this road. I’ve done that reverse engineering once for the Metz Fileformat 3-5. Not funny.
