### ISSUE TITLE
Panasonic TV

### ISSUE THREAD

**Issue by LuMy97** [PredatH0r/ChanSort#320]
Can't edit channel list on Panasonic TX-24JSW354.
The newest version of ChanSort gives me the error unknown channel list (channel list format: .db).
If it's possible please add also this TV to the compatible devices.

**Comment by PredatH0r** [comment]
I am currently working on an updated version specifically with improved support for the LS/LX series.

Early firmware versions seems to have had massive problems with internal channel management and created+exported lists with multiple channels using the same program number and multiple copies of the same channel at different numbers. So far I have not found a way to edit such a broken list in a way, that the TV will show it correctly in its EPG.

Anyhow, can you please send me your complete channel list as a zip (everything exported on the USB-stick)? 
I can then verify if this is the same format as LS/LX and if so, see if your file has data issues or not.

Best regards,
Horst

**Comment by LuMy97** [comment]
Here I have the complete channel list, exported from the TV. I hope you can resolve the problem.
[Uploading CLONE00001.zip…]()

**Comment by PredatH0r** [comment]
Unfortunately there is something wrong with the link.
It only shows "Uploading ..." and links back to the github issue page instead of a downloadable .zip file.
Alternatively you can send it to my email: horst at beham dot biz

**Comment by PredatH0r** [comment]
Thanks for your file.
It turns out that this particular model (amongst others) is based on the Vestel hard- and firmware (an OEM supplier for some Panasonic models and many other brands). 
Unfortunately after a firmware updates Vestel started to encrypt the exported channel list and changed the filename from settingsDB.db to settingsDB_enc.db.

With the files being encrypted, there is nothing I can do.
