### ISSUE TITLE
ChanSort_2022-11-29 saves in Chinese?

### ISSUE THREAD

**Issue by plueschpruem** [PredatH0r/ChanSort#326]
I just parsed the latest station search file from my Samsung and it seems that chanSort kinda corrupts the file on save into Chinese Lettering.
I was wondering, why my TV did not show any station names after uploading the list…
Re-opening the altered list shows what happened.
Looks like a encoding issue. Or did I miss some sort of setting?

Using the ChanSort_2021-05-01 I still had on that PC worked fine.
Before/after screenshots attached.

<img width="866" alt="before" src="https://user-images.githubusercontent.com/26715829/204666993-5faf53ce-f6bd-4497-ab85-2c04056b63c7.png">
<img width="898" alt="after" src="https://user-images.githubusercontent.com/26715829/204667003-900b3460-57ae-4e6d-af35-9365e28eeaf8.png">

**Comment by PredatH0r** [comment]
Thanks for the info, I am trying to find a solution for this asap.
This looks like a breaking incompatibility introduced in Microsoft's current version of the Sqlite database access library.

**Comment by PredatH0r** [comment]
This is fixed in https://github.com/PredatH0r/ChanSort/releases/tag/v2022-11-30
Samsung already stores the strings in a messed-up way, ChanSort needs to un-mess them when reading and re-mess them when writing. And the latter no longer worked after upgrading to a newer version of the Microsoft.Data.Sqlite library.
