### ISSUE TITLE
Save issue - No error is shown but edited list doesn't save to file - Hisense .db

### ISSUE THREAD

**Issue by alinturnagiu** [PredatH0r/ChanSort#329]
Hello,

I encountered a bug while trying to sort my Hisense TV (50E7HQ) channels.
Everything worked fine until i saved the changes to channels and re-opened the file and noticed that its the same channel list as the original. 
I receive no errors. The right side list is changing to the one i customized when i save, and a "servicelist.db.bak" file is created, but neither this .bak file or the .db file have the newly edited list.

I have another Samsung tv and tested to see if i encounter the same issue but i didn't. 

Version used is the 2022-12-04 one.
Please let me know if i can help with additional info.
Would be really grateful if this could be fixed.

.db file link just in case: https://file.io/ejts2IWGdE2r

[servicelist.zip](https://github.com/PredatH0r/ChanSort/files/10253518/servicelist.zip)

**Comment by PredatH0r** [comment]
The "Allow editing predefined lists (DANGEROUS)" option in the settings menu was ignored in the code that actually saved the list back to the file, which for safety reasons skipped all sub-lists that were loaded as read-only.
Hisense explicitly told me that LCN lists must not be modified. I can't tell what happens if they are.
My guess is that the channels will be automatically reordered as soon as they receive new LCN data from the DVB-C data stream.

Anyhow, the next ChanSort update will actually write changes to disk when the read-only mode is overridden.

But for above reasons I recommend that you check your TVs menu and disable any option for automatic channel updates and run a channel search without any predefined providers. Unfortunately I don't really know the exact options in the Hisense menu.

**Comment by alinturnagiu** [comment]
Thanks for looking into it.
I rescanned the channels according to your instructions and attached the new file in case it can be of use to you.

[servicelist.zip](https://github.com/PredatH0r/ChanSort/files/10300546/servicelist.zip)
