### ISSUE TITLE
Strange Error when trying to open an SCM file

### ISSUE THREAD

**Issue by stefanwalcz** [PredatH0r/ChanSort#56]
<img width="459" alt="bildschirmfoto 2017-01-28 um 19 58 45" src="https://cloud.githubusercontent.com/assets/25406784/22399047/53536f6e-e594-11e6-9fa7-8ba598bc68a5.png">

Hi I am trying to edit a channel list on Windows 10 (lastest version). (I do run it on my mac as a virtual machine in Parallels- all the latest versions available)

I am getting a strange message (see screenshot attached. can you gove me a hint on how to fix this? 

TIA 

Stefan

**Comment by PredatH0r** [comment]
This message means that the file is corrupt.
It is a common problem when using NTFS formatted USB sticks. Samsung TVs often have problem with those.
In most cases the problem can be avoided by using a stick formatted with FAT32.
I think one user reported that he had to run a new channel scan first - maybe due to a firmware upgrade.

SCM files are renamed ZIP files. If the file is valid, you should be able to open it with WinZIP, 7-Zip, WinRAR, ...
