### ISSUE TITLE
Sony support not possible?

### ISSUE THREAD

**Issue by ZwuselSepp** [PredatH0r/ChanSort#65]
Hello ChanSort-Team,

why is it not possible that you support with your great software Sony TV models? Because i have one and a samsung. And for the samsung i could use your perfect software but not for the sony ... :-(

Best regards,
ZwuselSepp

**Comment by PredatH0r** [comment]
Hi ZwuselSepp!

I don't have a Sony TV, which makes it quite difficult to develop and test my editor.
Also, there is a checksum in the file that I am not sure how to calculate. Without the right checksum, the TV will refuse to load the file.
And I also don't have the time to add and support more formats, since manufacturers constantly change their formats.

**Comment by laserjet6** [comment]
Hi Horst, 
Sony has their own channel editor app based on Java. It sucks; it's barely better than nothing. 
Wouldn't that help you bake in Sony support?

I understand this probably used to be a hobby that you don't have time for anymore, but it is still the best program for sorting channels there is. Sorting channels based on reference list is so brilliant and so simple an idea I don't understand why its not build in every (supposedly smart) TV. 

Greetings from Slovakia, 
Peter
