### ISSUE TITLE
lg-47LB650V not restoring satellite channels  

### ISSUE THREAD

**Issue by martinfitzg** [PredatH0r/ChanSort#66]
TV - lg-47LB650V 
Software Version - 05.05.35
webOS 1.4.0-2525

ChanSort 2017-01-26 (v2)

Hello all, getting an issue when I'm trying to restore a backup. All the DTV channels restore but the satellite channels do not. The sat channels are in the file and the tv restarts after the restore reporting no issues, but switch to satellite mode in the tv and it says there is no channels tuned in.  Any one seeing this issue or know a way around it.

**Comment by PredatH0r** [comment]
Restoring a backup can fail when you upgraded the firmware in the meantime or ran a new channel search, especially when satellite channels were set up with a predefined list instead of a full blindscan.

Depending on firmware version it may also depend on whether you have only the GlobalClone file, only the xxLB650V.TLL or both files on your USB stick when you import it back.

To get to a clean state, I recommend resetting the TV to factory defaults, run a full channel search (not selecting any predefined service providers), export the new list and use the old list as a reference list to apply the same order. The TV should then be able to read the new list again.
