### ISSUE TITLE
leo77

### ISSUE THREAD

**Issue by leokop** [PredatH0r/ChanSort#86]
Panasonic tx55as630e,,nelze pusti???

**Comment by leokop** [comment]
smart tv nelze pust aplikace channel Deutsh...

**Comment by PredatH0r** [comment]
Deleting of channels is disabled for many TV models because the TV will automatically find unknown channels again and adds them back into the list.
The recommended way is to set a channel to "hidden" and "skip" so that it doesn't show in the EPG and won't be selected when zapping with Pr+/- on your remote
