### ISSUE TITLE
Not working with LG

### ISSUE THREAD

**Issue by khafez78** [PredatH0r/ChanSort#92]
This program didn't work for LG Smart TV webOS model number 43LJ550V.
After import, the TV re-started un-programmed.
Please advice.

**Comment by PredatH0r** [comment]
Which version / build date of the program did you use?
There was an issue that I fixed a few days ago that i fixed in version 2017-11-30, which caused problem when channels were deleted and not appended to the end when saving.
If you used that version, can you please upload your original (.bak) and modified channel list files so I can try to find out what might be wrong in there?
Also, did you use a FAT32 formatted stick? TVs sometimes read or write garbage when the stick is formatted with NTFS.

**Comment by khafez78** [comment]
I was using this version (2017-11-30), but I selected to delete the unsorted channels and this didn't work.
I repeated the process while appending them to the end of the list and this worked.
Thank you.
